"""tweak instruments name enum

Revision ID: 6f009a618b9b
Revises: 98e054680a79
Create Date: 2025-12-01 15:50:16.229645

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from app.models.instrument import InstrumentNameEnum


# revision identifiers, used by Alembic.
revision: str = '6f009a618b9b'
down_revision: Union[str, Sequence[str], None] = '98e054680a79'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


instrument_name_enum = sa.Enum(
    InstrumentNameEnum,
    name="instrument_name_enum",
)

def upgrade() -> None:
    """Upgrade schema."""
    
    bind = op.get_bind()
    instrument_name_enum.create(bind, checkfirst=True)
    
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('instruments', 'name',
                existing_type=sa.VARCHAR(),
                type_=sa.Enum('ES', 'NQ', 'YM', name='instrument_name_enum'),
                postgresql_using="name::text::instrument_name_enum",
                nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    bind = op.get_bind()
    
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('instruments', 'name',
                existing_type=sa.Enum('ES', 'NQ', 'YM', name='instrument_name_enum'),
                type_=sa.VARCHAR(),
                postgresql_using="name::text",
                nullable=True)

    instrument_name_enum.drop(bind, checkfirst=True)
    # ### end Alembic commands ###