"""create instruments table

Revision ID: 8be069d1001b
Revises: 976dc861b36c
Create Date: 2025-12-01 14:19:50.064542

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8be069d1001b'
down_revision: Union[str, Sequence[str], None] = '976dc861b36c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('instruments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_instruments_name'), 'instruments', ['name'], unique=True)
    op.create_table('instruments_prices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_instruments_prices_name'), 'instruments_prices', ['name'], unique=True)
    op.drop_index(op.f('ix_users_id'), table_name='users')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.drop_index(op.f('ix_instruments_prices_name'), table_name='instruments_prices')
    op.drop_table('instruments_prices')
    op.drop_index(op.f('ix_instruments_name'), table_name='instruments')
    op.drop_table('instruments')
    # ### end Alembic commands ###
