"""price in instruments price changed

Revision ID: 949ecd852f24
Revises: 93fc096d97c5
Create Date: 2025-12-01 17:11:12.973001

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '949ecd852f24'
down_revision: Union[str, Sequence[str], None] = '93fc096d97c5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('instruments_prices', 'price',
               existing_type=sa.NUMERIC(precision=2, scale=0),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('instruments_prices', 'price',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=sa.NUMERIC(precision=2, scale=0),
               existing_nullable=False)
    # ### end Alembic commands ###
