"""tweak instruments_price table

Revision ID: 98e054680a79
Revises: 8be069d1001b
Create Date: 2025-12-01 14:27:24.334175

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '98e054680a79'
down_revision: Union[str, Sequence[str], None] = '8be069d1001b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('instruments_prices', sa.Column('instrument_id', sa.Integer(), nullable=False))
    op.add_column('instruments_prices', sa.Column('price', sa.Numeric(precision=2), nullable=False))
    op.drop_index(op.f('ix_instruments_prices_name'), table_name='instruments_prices')
    op.create_index(op.f('ix_instruments_prices_instrument_id'), 'instruments_prices', ['instrument_id'], unique=False)
    op.create_foreign_key(None, 'instruments_prices', 'instruments', ['instrument_id'], ['id'], ondelete='CASCADE')
    op.drop_column('instruments_prices', 'name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('instruments_prices', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint("", 'instruments_prices', type_='foreignkey')
    op.drop_index(op.f('ix_instruments_prices_instrument_id'), table_name='instruments_prices')
    op.create_index(op.f('ix_instruments_prices_name'), 'instruments_prices', ['name'], unique=True)
    op.drop_column('instruments_prices', 'price')
    op.drop_column('instruments_prices', 'instrument_id')
    # ### end Alembic commands ###
